baseURL = "https://glyh.github.io/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "en-us"
# 网站语言, 仅在这里 CN 大写
languageCode = "en-us"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "Newbie@Corner"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "CodeIT"

[params]
  # LoveIt 主题版本
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "Posts"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  lineNos = true
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[params.page.math]
  enable = true
  # KaTeX 插件 copy_tex
  copyTex = true
  # KaTeX 插件 mhchem
  mhchem = true

[author]
  name = "lyhokia"
  email = "lyhokia@gmail.com"
